//////////////////////////////////////Try and catch/////////////////////////////////////////////////////////////////////////////

//syntax

/////////////////////////////////////////////////////ex1//////////////////////////////////////////////////////////

// try{
//     // logical error
//     console.log(Ajay);
//     }
// catch(err){
//     // error handling message
//     console.log(err.name);
//    }

/////////////////////////////////////////////////////////////////////ex2/////////////////////////////////////////

try{
    let firstname = "Anurag";
    console.log(firstname + "" + lastname);
}
catch(err){
    console.log(err.name , "variable name missing");
}
finally{
    console.log("Main to chalunga")
}

////////////////////////////////////////////////Throw/////////////////////////////////////////////////////////////
// The throw statement allows you to create a custom error.
// Technically you can throw an exception (throw an error).
// The exception can be a JavaScript String, a Number, a Boolean or an Object:

// throw "Too big";    // throw a text
// throw 500;          // throw a number



////////////////////////////////////////type of error////////////////////////////////////////////////////////////////
//reference error
//syntax error
//type error